### ISSUE TITLE
cmd/fillstruct: Don't fill system fields when filling structs generated by protoc (gRPC)

### ISSUE THREAD

**Issue by asankov** [davidrjenni/reftools#34]
When using gRPC, you get your struct models generated, based on your `protobuf` definitions. The generated structs contain some "system" fields, which hold additional data for you, but you never fill them explicitly. 
Example: for this `.proto` file:
```protobuf
message Response {
  string message = 1
}
```
you get this `go` code generated:
```golang
type Response struct {
  Message string
  XXX_NoUnkeyedLiteral struct{} `json:"-"`
  XXX_unrecognized     []byte   `json:"-"`
  XXX_sizecache        int32    `json:"-"`
}
```
the last 3 fields are the ones I am talking about - they are used by gRPC internally and you almost never interact with them. 

When using `fillstruct` with gRPC messages I don't want and don't need to have this pop-up my code.

Current behaviour:
```golang
r := &Response{}
// fillstruct
r := &Response{
    Message: ""
    XXX_NoUnkeyedLiteral: struct{}{},
    XXX_unrecognized:     nil,
    XXX_sizecache:        0,
}
```

expected behaviour:
```golang
r := &Response{}
// fillstruct
r := &Response{
    Message: ""
}
```
I am willing to help with the design/implementation of this, if you think it makes sense to have this build into the tool

**Comment by asankov** [comment]
any update on this?

as mentioned - I am willing to implement this myself, if you would this to be added into the tool?

**Comment by davidrjenni** [comment]
@asankov, I don't work much with gRPC and protobufs, but based on your explanation the proposed change is generally useful for all users of the tool (or does not affect them).
A PR is definitely welcome. I will try to review and merge it in a timely manner.

If you want to discuss the design of the change first, we can do that e.g. in this issue.
